name: Keep Render App Awake
on:
  schedule:
    - cron: '*/10 * * * *'  # 10分ごとに実行
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render app
        run: curl -s https://md-tool-1.onrender.com > /dev/null

